export const cartActionTypes = {
    TOGGLE_CART_VISIBILITY: "TOGGLE_CART_VISIBILITY",
    ADD_ITEM: "ADD_ITEM",
    REMOVE_ITEM_FROM_CART: "REMOVE_ITEM_FROM_CART",
    DECREASE_NUM_OF_ITEM: "DECREASE_NUM_OF_ITEM"
}